spring:
  profiles:
    active: ${PROFILE}
  main:
    allow-bean-definition-overriding: true
  jpa:
    database: POSTGRESQL
    show-sql: true
    generate-ddl: true
  thymeleaf:
    cache: "false"
    prefix: classpath:/views/
    suffix: .html
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/polygis}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:test}
    driverClassName: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
      connection-timeout: 20000
server:
  port: 9000
logging:
  level:
    org:
      springframework:
        security:
          web:
            FilterChainProxy: DEBUG
app:
  bmc:
    secret: ${BMC_SECRET}
    signature-header: ${BMC_SIGNATURE_HEADER:x-signature-sha256}
  credentials:
    superadmin:
      username: ${SUPERADMIN_USERNAME}
      password: ${SUPERADMIN_PASSWORD}
    admin:
      username: ${ADMIN_USERNAME}
      password: ${ADMIN_PASSWORD}
    user:
      username: ${USER_USERNAME}
      password: ${USER_PASSWORD}